const mongoose = require('mongoose');
const dotenv = require('dotenv');
const BlogPost = require('../models/BlogPost');

// Load env vars
dotenv.config({ path: '../.env' });

const posts = [
  {
    title: 'The AI Revolution in Global Development Tracking',
    slug: 'ai-revolution-global-development',
    excerpt: 'How machine learning models are fundamentally changing how we track and predict global human development metrics.',
    content: `For decades, tracking global development has relied on retrospective data collection—a process that often takes years to compile and verify. By the time policymakers see the numbers, the reality on the ground has already changed. Enter Artificial Intelligence.

Machine learning models, like the one powering HDI Insight, represent a paradigm shift. Instead of merely recording the past, these systems analyze complex patterns in real-time to forecast the future. By ingesting vast datasets ranging from life expectancy to expected years of schooling, neural networks can identify subtle correlations that human analysts might miss.

This shift from reactive to proactive development tracking enables non-governmental organizations and governments to allocate resources more efficiently. If an algorithm predicts a drop in the HDI score of a specific region due to a plateau in GNI per capita, interventions can be planned before the crisis fully materializes. 

As we refine these models, the goal is to incorporate even more dynamic variables, such as real-time satellite imagery to assess economic activity or localized health data to predict life expectancy trends. The future of development economics is undeniably driven by data.`,
    author: 'Dr. Evelyn Carter',
    category: 'Technology',
    readTimeMinutes: 5,
    isPremiumOnly: false,
  },
  {
    title: 'Beyond GDP: Why the Human Development Index Matters',
    slug: 'why-hdi-matters',
    excerpt: 'Economic growth alone does not equal human progress. Understanding the holistic approach of the HDI.',
    content: `It is easy to look at a country's Gross Domestic Product (GDP) and assume that a high number equates to a high quality of life. However, this purely economic perspective masks severe inequalities and overlooks the fundamental components of a fulfilling human life. This is why the Human Development Index (HDI) was introduced by the United Nations in 1990.

The HDI forces us to ask a critical question: What good is immense national wealth if the citizens are not living long, healthy, and educated lives? 

By factoring in life expectancy at birth, the HDI captures the effectiveness of a nation's healthcare system and nutritional standards. By incorporating mean and expected years of schooling, it reflects the accessibility and quality of education. Finally, by including Gross National Income (GNI) per capita, it acknowledges that a decent standard of living is necessary to unlock human potential.

The geometric mean of these three dimensions ensures that poor performance in any single area cannot be completely masked by exceptional performance in another. A country cannot simply buy its way to the top of the HDI rankings if its citizens are uneducated and unhealthy. In this way, the HDI remains one of the most robust and humane ways to measure the true progress of a society.`,
    author: 'Michael Osei',
    category: 'Development',
    readTimeMinutes: 6,
    isPremiumOnly: false,
  },
  {
    title: 'Advanced Predictive Analytics for Policy Making',
    slug: 'advanced-predictive-analytics',
    excerpt: 'Deep-dive into the statistical methodologies used to forecast HDI categories for emerging economies.',
    content: `Predicting a nation's development trajectory requires more than simple linear regression. When dealing with macro-economic and social indicators, the relationships between variables are highly non-linear. For example, the impact of an additional year of schooling on GNI per capita is vastly different in a low-income country compared to a high-income one.

Our predictive models at HDI Insight utilize advanced ensemble methods, specifically Random Forests and Gradient Boosting Machines, to capture these non-linear dynamics. These models build hundreds of decision trees, each trained on a random subset of data, and aggregate their predictions to produce a highly accurate and stable forecast.

In this premium report, we analyze the feature importance scores generated by our latest model iteration. Unsurprisingly, Life Expectancy remains the strongest anchor predictor. However, our recent findings indicate that Expected Years of Schooling is rapidly becoming the leading indicator for upward mobility from the 'Medium' to 'High' HDI category. 

Policymakers in emerging economies should take note: while immediate economic stimulus (boosting GNI) provides a short-term HDI bump, long-term stability in the 'Very High' category is statistically impossible without aggressive investment in educational infrastructure.`,
    author: 'AI Research Group',
    category: 'Analytics',
    readTimeMinutes: 8,
    isPremiumOnly: true,
  },
  {
    title: 'The Stagnation Danger: Analyzing the "Middle-Income Trap"',
    slug: 'middle-income-trap-analysis',
    excerpt: 'Why do so many countries stall in the "Medium HDI" category, and how can they break out?',
    content: `The "Middle-Income Trap" is a well-documented economic phenomenon where a rapidly growing economy stagnates at middle-income levels and fails to transition to a high-income economy. In the context of the HDI, we see a parallel issue: The Medium HDI Plateau.

Countries typically escape the "Low HDI" category through basic public health interventions (vaccinations, clean water) and primary education initiatives. These yield massive, rapid improvements in life expectancy and basic literacy. However, moving from "Medium" to "High" or "Very High" HDI requires a structural shift.

It requires moving from an economy based on cheap labor and raw material export to one driven by innovation, high-tech manufacturing, and services. This transition mandates a workforce with tertiary education (reflected in high Mean Years of Schooling) and a robust healthcare system capable of managing chronic diseases, not just infectious ones.

Our machine learning models have identified a critical threshold: If a country's GNI per capita grows by 20% but its Mean Years of Schooling remains flat over a five-year period, the probability of stalling in the Medium HDI category for the next decade exceeds 85%.`,
    author: 'Sarah Jenkins',
    category: 'Economics',
    readTimeMinutes: 6,
    isPremiumOnly: true,
  },
  {
    title: 'Climate Change: The Unseen Variable in Development',
    slug: 'climate-change-hdi',
    excerpt: 'How environmental degradation threatens to reverse decades of progress in global health and education.',
    content: `The traditional HDI model has a glaring blind spot: it does not account for environmental sustainability. A country can theoretically achieve a "Very High" HDI score through rapid industrialization fueled by extreme ecological destruction. However, this is a short-term illusion.

Climate change is already impacting the core pillars of the HDI. Extreme heat and shifting disease vectors are threatening life expectancy. Agricultural failures due to droughts are impacting economic stability (GNI), and climate-induced migrations are disrupting education systems globally.

The UNDP recently introduced the Planetary pressures-adjusted HDI (PHDI), which discounts the standard HDI by the level of carbon dioxide emissions and material footprint per capita. When this adjustment is applied, the global rankings shift dramatically. Nations that previously celebrated top-tier status suddenly drop, revealing that their development was essentially borrowed from the future.

As predictive models evolve, incorporating climate risk factors into standard development forecasts will no longer be optional—it will be essential for creating an accurate picture of human resilience.`,
    author: 'Environmental Desk',
    category: 'Environment',
    readTimeMinutes: 7,
    isPremiumOnly: false,
  },
  {
    title: 'Education Inequality and the Gini Coefficient',
    slug: 'education-inequality-gini',
    excerpt: 'Examining how disparity in schooling access creates compounding negative effects on national development.',
    content: `When we look at 'Mean Years of Schooling' as a national average, we often miss the story told by the distribution of that education. Two countries might both average 8 years of schooling, but if one achieves this by having half its population complete high school while the other half has no formal education, the developmental outcomes will be drastically different from a country where everyone completes exactly 8 years.

This disparity is measured using inequality indices, similar to the Gini coefficient used for income. High education inequality severely bottlenecks economic development. A modern, innovation-driven economy cannot function if a large segment of the population lacks basic literacy and numeracy.

Furthermore, educational inequality strongly correlates with health inequality. Populations with lower educational attainment consistently show lower life expectancies due to a lack of health literacy and reduced access to preventative care. 

To improve their HDI scores efficiently, developing nations must focus not just on raising the average years of schooling (often achieved by pushing the already-educated through university), but on raising the floor—ensuring universal access to quality primary and secondary education.`,
    author: 'Dr. Evelyn Carter',
    category: 'Education',
    readTimeMinutes: 5,
    isPremiumOnly: false,
  }
];

const seedDB = async () => {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
      console.error('Error: MONGO_URI environment variable is not defined.');
      process.exit(1);
    }
    await mongoose.connect(mongoUri);
    console.log('MongoDB Connected');

    await BlogPost.deleteMany({});
    console.log('Old blog posts removed');

    await BlogPost.insertMany(posts);
    console.log('New blog posts seeded');

    process.exit();
  } catch (error) {
    console.error(`Error: \${error.message}`);
    process.exit(1);
  }
};

seedDB();
